function H_YAW = calcH_YAW321(q0,q1,q2,q3)
%CALCH_YAW321
%    H_YAW = CALCH_YAW321(Q0,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    17-Dec-2018 21:14:30

t2 = q0.^2;
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = t2+t3-t4-t5;
t7 = q0.*q3.*2.0;
t8 = q1.*q2.*2.0;
t9 = t7+t8;
t10 = 1.0./t6.^2;
t11 = t9.^2;
t12 = t10.*t11;
t13 = t12+1.0;
t14 = 1.0./t13;
t15 = 1.0./t6;
H_YAW = [0.0,t14.*(t15.*(q0.*q1.*2.0-q2.*q3.*2.0)+t9.*t10.*(q0.*q2.*2.0+q1.*q3.*2.0)),t14.*(t15.*(t2-t3+t4-t5)+t9.*t10.*(t7-t8)),0.0,0.0,0.0,0.0,0.0,0.0];
